Ticket1b
trevorjr31/fun-kickoff-project pull request #11
Opened 2021-11-09 18:42 UTC by trevorjr31

### What this PR does (required): 

PR for Ticket #1 
- Edit Login/Signup pages to match mockup
- Added responsive Navbar to pages

### Screenshots / Videos (front-end only):
![Screenshot (125)](https://user-images.githubusercontent.com/77120652/140983871-17dc17fc-baf3-4e9a-bba1-ec85717189d4.png)
![Screenshot (126)](https://user-images.githubusercontent.com/77120652/140983874-d3cd72ee-33c1-439a-bec8-a9d323d7d778.png)
![Screenshot (127)](https://user-images.githubusercontent.com/77120652/140983875-f445531e-e537-4c2f-8b84-16c206ebd3fd.png)
![Screenshot (128)](https://user-images.githubusercontent.com/77120652/140983876-96dfd3ab-de63-415c-af18-788678f7664e.png)

### Any information needed to test this feature (required):
- Responsive display will be shown on small and extra small screens
   -each responsive menu item will behave as its corresponding link behaves
- Become a sitter link will go to signup page
- Forms on both pages are already functional

### Any issues with the current functionality (optional):
N/A

2021-11-09 20:34 UTC, ezeilo-su requested changes
Nice job on this one. Please consider all the comments as avoid CAPITALCASE for text and address them according to my first comment in the PR.
Happy coding!

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          BECOME A SITTER
Please avoid using CAPITALCASE for text, some screen readers interpret this text as abbreviations, you can resort to using a CSS class to transform text instead.

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          LOGIN
The same comment as above

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          SIGN UP
The same thing here

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          SIGN UP
The same thing here

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +            <Typography className={classes.textlink}>BECOME A SITTER</Typography>
Change this one to lower case too

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +            <Typography className={classes.textlink}>LOGIN</Typography>
The same here

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +            <Typography className={classes.textlink}>SIGNUP</Typography>
This one

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <Typography className={classes.label}>EMAIL ADDRESS</Typography>
This one too

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <Typography className={classes.label}>PASSWORD</Typography>
This one

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>EMAIL ADDRESS</Typography>
Same with this one

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>NAME</Typography>
Avoid capital casing for text :smile:

2021-11-09 20:34 UTC, ezeilo-su commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>PASSWORD</Typography>
The same thing here

2021-11-09 21:29 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          BECOME A SITTER
Will make the changes. I didn't realize it mattered thank you for letting me know about that.

2021-11-09 21:29 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          LOGIN
Fixed.

2021-11-09 21:29 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          SIGN UP
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarLinks.tsx
> +          SIGN UP
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +            <Typography className={classes.textlink}>BECOME A SITTER</Typography>
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <Typography className={classes.label}>EMAIL ADDRESS</Typography>
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>EMAIL ADDRESS</Typography>
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>NAME</Typography>
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>PASSWORD</Typography>
Fixed.

2021-11-09 21:30 UTC, trevorjr31 commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <Typography className={classes.label}>EMAIL ADDRESS</Typography>
Fixed.

2021-11-09 21:31 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +            <Typography className={classes.textlink}>LOGIN</Typography>
Fixed.

2021-11-09 21:31 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +            <Typography className={classes.textlink}>SIGNUP</Typography>
Fixed.

2021-11-10 10:21 UTC, ugur-akin reviewed
Looks very good! Good use of React, I mentioned a few general issues as well as some about Material UI. Don't hesitate to comment for any further thoughts or discussions 👍🏼

2021-11-10 10:21 UTC, ugur-akin commented on client/src/pages/SignUp/SignUpForm/useStyles.ts
> +  },
We seem to be doing this for all the input fields so far, maybe it's better if we *a)* create a reusable component for this or *b)* apply this override at the theme level? 

a) Checkout item 3 [here](https://v4.mui.com/customization/components/#customizing-components).
b) Checkout [this](https://v4.mui.com/customization/components/#global-theme-override).

2021-11-10 10:21 UTC, ugur-akin commented on client/src/themes/theme.ts
> +    primary: { main: '#FF0000' },
The color of the logo seems to be `#F04040` 👍🏼 You can use a tool like [eye dropper](https://chrome.google.com/webstore/detail/eye-dropper/hmdcmlfkchdmnmnmheododdhjedfccka?hl=en) when not provided with the color code in your mocks.

2021-11-10 10:21 UTC, ugur-akin commented on server/sample.env
> +TEAM_NAMES=Bonnie,Sina,Trevor
This is something we usually want to avoid - we should only include changes from **one** feature/branch in our PRs. This case is quite forgiving as the only change from the other feature/branch is in `sample.env`. If we include a complex feature within another, changes get overwhelming very quickly and it becomes difficult to manage, maintain and review 👍🏼 

The usual way we avoid this is by branching each feature off of main as well as only staging/committing the relevant changes (e.g. don't stage a local change made for testing).

2021-11-10 10:21 UTC, ugur-akin commented on client/src/components/NavBar/NavBarLinks/loggedOut/useStyles.ts
> +    backgroundColor: theme.palette.primary.main,
You should be able to get rid of most of the css here (there seems to be multiple occurrences of the same issue throughout) since you provide `variant/color/size` props already 👍🏼

2021-11-10 15:31 UTC, trevorjr31 commented on client/src/components/NavBar/NavBar.tsx
> +      <CssBaseline />
Thank you, I was not aware of the scope of cssbaseline. Fix applied app-wide

2021-11-10 15:47 UTC, trevorjr31 commented on client/src/components/NavBar/NavBar.tsx
> +      <Box className={classes.navWrapper}>
I usually just put all styles together for consistency. Using the Box component as you suggested helps readability of the component file to understand the layout. I made the change where box styles were shorter and more layout based and kept more lengthier styled boxes in the styles file. 

In some places there are inconsistent stylings (I kept styles for the box with shadow in the style file) .Is this ok?
```
<Box className={classes.authWrapper}> 
    <Typography className={classes.welcome}>Welcome back</Typography>
    <Box width="100%" maxWidth={450} p={3} alignSelf="center">
          <LoginForm handleSubmit={handleSubmit} />
    </Box>
</Box>
```

2021-11-10 15:50 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +        aria-controls="basic-menu"
For sure. I will work on proof-reading my code one more time before submitting PRs to prevent this kind of thing. Better yet I will properly id the component when I implement it.

2021-11-10 15:50 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +        aria-controls="basic-menu"
Fixed.

2021-11-10 15:50 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +      >
Fixed.

2021-11-10 15:51 UTC, trevorjr31 commented on client/src/pages/SignUp/SignUpForm/useStyles.ts
> +  },
Applied an override in the theme for this and button hover which was similarly repeated. This will be useful for scalability as we develop the rest of the UI. Thanks

2021-11-10 15:54 UTC, trevorjr31 commented on server/sample.env
> +TEAM_NAMES=Bonnie,Sina,Trevor
I reverted this change so it is no longer reflected in this branch.

2021-11-10 15:55 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/useStyles.ts
> +    backgroundColor: theme.palette.primary.main,
I was able to refactor and remove a bunch from each button style. Also added a theme override as mentioned above.

2021-11-10 15:56 UTC, trevorjr31 commented on client/src/themes/theme.ts
> +    primary: { main: '#FF0000' },
Thank you for the tip! I just googled 'red hex' and used that...not very accurate

2021-11-10 15:57 UTC, trevorjr31 commented on client/src/themes/theme.ts
> +    primary: { main: '#FF0000' },
Fixed

2021-11-11 12:49 UTC, rajivtitus commented on client/src/App.tsx
> +              <CssBaseline />
👍🏽

2021-11-11 12:55 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <div style={{ height: 95, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
Please avoid usage of inline styles :)

2021-11-11 13:03 UTC, rajivtitus reviewed
Good work here and thanks for making the requested changes. Just some minor comments for you to have a look. Thanks :)

Note: Please remember to use meaningful branch names so it's easier to track (for example, feature-signup-login-pages)

2021-11-11 13:03 UTC, rajivtitus commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +        <MenuItem onClick={handleClose}>
You can combine MenuItem and react-router's Link.

```
<MenuItem
    component={Link}
    to="/login"
    className={classes.link}
    onClick={handleClose}
>
    login
</MenuItem>
```

2021-11-11 13:16 UTC, trevorjr31 commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <div style={{ height: 95, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
I will remember to do this, thanks. Here I instead chose to use a box with display properties to keep things consistent.

2021-11-11 13:17 UTC, trevorjr31 commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <div style={{ height: 95, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
Fix applied.

2021-11-11 13:17 UTC, trevorjr31 commented on client/src/themes/theme.ts
> +    primary: { main: '#F04040' },
Eye dropper!

2021-11-11 13:18 UTC, trevorjr31 commented on client/src/components/NavBar/NavBarLinks/loggedOut/NavBarMenu/NavBarMenu.tsx
> +        <MenuItem onClick={handleClose}>
Done! I did this with the buttons in the regular view but didn't initially realize to refactor it here also.

2021-11-11 13:19 UTC, rajivtitus approved these changes
LGTM! Great work here 👍🏽

2021-11-11 13:22 UTC, trevorjr31 commented
Thank you for all of the great constructive feedback 💪

2021-11-12 18:22 UTC, merged